### ISSUE TITLE
Making this addon 1.17 compatible

### ISSUE THREAD

**Issue by blazebuilderx** [Offroaders123/Dark-Mode#1]
please @Offroaders123 can you make this addon 1.17 compatible with the achievement screen and the panorama etc.

**Comment by Gengar-lab** [comment]
Yes plz @Offroaders123 🙏

**Comment by Offroaders123** [comment]
I started working on the update s few days ago. I'm a little behind on things right now, so it will be out in the next week or so.

**Comment by Offroaders123** [comment]
Sorry for taking so long on this update, more features and changes have come up during development. I looked back on a lot of the original textures of the pack and realized a lot of them are either inconsistent in regards to styling, or aren't color-accurate with the current textures in the Vanilla resource pack.

**Comment by Offroaders123** [comment]
Alright! My bad for leaving Dark Mode in the dark, haha. Everything is up to date as of the Wild Update. I am working on publishing a new release for all of the changes soon. Now it uses the new Mangrove Swamp panorama!

![image](https://user-images.githubusercontent.com/65947371/168401971-e29126d4-8a51-4c4a-86db-e64d540a94e4.png)
