### ISSUE TITLE
Unnecessary psd files

### ISSUE THREAD

**Issue by Gengar-lab** [Offroaders123/Dark-Mode#2]
I downloaded git repo to try on bedrock.
I was wondering why previous version had size just around 6mb and current repo version around 19mb.

I found that there are unneeded **panorama_halloween.psd** and **title - modern.psd** in [Bedrock/textures/ui](https://github.com/Offroaders123/Dark-Mode/tree/main/Bedrock/textures/ui) folder which significantly increased pack size.

**Comment by Offroaders123** [comment]
Oops sorry about that
I added that temporarily so it can be part of the version history of the pack.
I was gonna remove it in the next update.

**Comment by Offroaders123** [comment]
I've been working on support for Caves & Cliffs and the Wild Update the last few days, so I removed those extra PSD files from the folder structure. Sorry it took so long!
