### ISSUE TITLE
One part of Marketplace is not retextured

### ISSUE THREAD

**Issue by Rafii2198** [Offroaders123/Dark-Mode#5]
The "See more" or "Show more" (I believe it is called like that in English) button have that default, unchanged frame 
![obraz](https://user-images.githubusercontent.com/26695327/155422921-beb9e779-6c8d-4cc6-b916-fb60d3eca398.png)

**Comment by Offroaders123** [comment]
Thanks for submitting the bug report! I hadn't noticed this one myself. A fix for it is in the works at the moment.

![Show More button wrapper](https://user-images.githubusercontent.com/65947371/169942856-4d42fecb-9c3f-4e3b-9532-1740753f47f8.png)
