### ISSUE TITLE
Suggestion: Nintendo Switch and other consoles.

### ISSUE THREAD

**Issue by ZeldasWetDream** [Offroaders123/Dark-Mode#7]
Do you have plans on putting this on the bedrock store so it can be accessible to the console plebs, like me and many others, who want to have a better viewing experience?

**Comment by Offroaders123** [comment]
I looked into applying for a Marketplace Partnership around a year ago, and their team never responded to my submission unfortunately. So I'm not sure if it will be on the Marketplace, for the time being at least.
