### ISSUE TITLE
Mouse doesn't lock

### ISSUE THREAD

**Issue by ArduinoFan0** [Offroaders123/Dark-Mode#8]
I can't even use the pack because of a simple bug on mobile with keyboard and mouse controls that prevents your cursor from hiding when joining a world

**Comment by Offroaders123** [comment]
Is this when playing on Android or iOS, or both?

**Comment by ArduinoFan0** [comment]
It's on an Android 7 emulator for Windows

**Comment by Offroaders123** [comment]
Does the bug still happen without using Dark Mode?

**Comment by ArduinoFan0** [comment]
It happens only while using dark mode

**Comment by Offroaders123** [comment]
I'm not sure this is an issue specific to Dark Mode, I tried reproducing the same error with a keyboard and mouse on my iPad, and it works without error there. It could be possible that your emulator isn't enabling pointer lock as expected? What emulator are you using to run the game?

**Comment by ArduinoFan0** [comment]
I'm using Bluestacks

**Comment by Offroaders123** [comment]
Does this prevent the issue?
https://support.bluestacks.com/hc/en-us/articles/4404839026701-How-to-lock-and-unlock-your-mouse-cursor-on-BlueStacks-5

**Comment by ArduinoFan0** [comment]
I already tried that and it wouldn't let me rotate my camera more than 360° either way

**Comment by Offroaders123** [comment]
It sounds like it's detecting the mouse motion correctly, but the mouse lock surface isn't connecting properly with your host OS. So I think this is something to do with how Bluestacks and Android are pairing with Windows' mouse lock. I think the mouse lock is working in the Android portion, but not in Windows for some reason.

It looks like it could be a configuration setting you can change within Bluestacks' controls options to fix it.
https://www.reddit.com/r/BlueStacks/comments/v5s0n0/can_i_lock_my_cursor_into_the_crosshair_in/
https://support.bluestacks.com/hc/en-us/articles/360061179732-How-to-update-controls-for-a-game-on-BlueStacks-5
