### ISSUE TITLE
A double/large chest becomes a single chest

### ISSUE THREAD

**Issue by Flonja** [Offroaders123/Dark-Mode#9]
![image](https://github.com/Offroaders123/Dark-Mode/assets/20887403/b87e4185-0674-4a38-8dc0-aea65382ea2d)

**Comment by Offroaders123** [comment]
I think it looks like you have another resource pack applied that's trying to override the code for the chest UI that Dark Mode adds. It looks like it's working as intended when using Dark Mode only.

<img width="1512" alt="Dark Mode Double Chest UI" src="https://github.com/Offroaders123/Dark-Mode/assets/65947371/37677334-4681-41d7-a715-3d48b2f1d249">

**Comment by Flonja** [comment]
I'll take a look which other texture pack interferes

**Comment by Flonja** [comment]
So after going through my texture pack list, i couldn't find another enabled pack that changed `chest_screen.json`, so I renamed the one in Dark Mode to `chest_screen.json.bak` and that fixed it.
My local file: [chest_screen.json](https://github.com/Offroaders123/Dark-Mode/files/11971091/chest_screen.txt)

**Comment by Offroaders123** [comment]
One other thing I can think of is that Dark Mode's `chest_screen.json` file relies on other vanilla files that might be changed by another pack, like `ui_common.json`.

I'll start looking into my UI files to see what I can do to fix them, I think `mob_effect_screen.json` might be out of date as of recent game versions too.

Does the Chest UI still have issues when applying Dark Mode on top of your other resource packs? I think that could be another fix for it too.

**Comment by Flonja** [comment]
> Does the Chest UI still have issues when applying Dark Mode on top of your other resource packs? I think that could be another fix for it too.

That does indeed fix it too. (weirdly enough)

**Comment by Offroaders123** [comment]
Aah ok glad it fixed it! So somewhere it is colliding with another pack you have.

**Comment by Flonja** [comment]
Maybe as `ui_common.json` as stated?

**Comment by Offroaders123** [comment]
It fixes it because when Dark Mode is on top, it will override the other packs that are below it. And it was doing the same thing the other way around, when one of your other packs was on top of Dark Mode. But since Dark Mode has a custom screen file, the other pack expects the vanilla one, so it get all bugged out like that.

**Comment by Offroaders123** [comment]
> Maybe as `ui_common.json` as stated?

Yeah it might be that.

**Comment by Offroaders123** [comment]
If you move Dark Mode up and down through the list of packs, you can test which one has to be on top of Dark Mode for it to start showing the bug.
